---
# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mono-to-actualbudget
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mono-to-actualbudget
              image: 2xnone/mono-to-actualbudget:0.0.1
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - node mono_actual.js
